In [1]:
pip install pandas sqlalchemy pyodbc matplotlib seaborn

Requirement already satisfied: pandas in c:\users\sara\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\sara\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\users\sara\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: matplotlib in c:\users\sara\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\users\sara\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sara\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sara\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sara\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sara\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sara\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sara\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sara\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: six>=1.5 in c:\users\sara\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
from sqlalchemy import text
from database import engine
import numpy as np

print("Konekcija uspešna!")

--- USPEŠNO KONFIGURISAN ENGINE SA DRAJVEROM: {SQL Server} ---
Konekcija uspešna!

In [3]:
sql_query = text("""
    DECLARE @MaxDate DATETIME = (SELECT MAX(Ts) FROM dbo.MeterReadTfes);
    
    SELECT 
        m.Mid AS meter_id, 
        m.Val AS value, 
        m.Ts  AS timestamp
    FROM dbo.MeterReadTfes m
    JOIN dbo.Meters me ON m.Mid = me.Id
    JOIN dbo.DistributionSubstation ds ON ds.MeterId = me.Id
    WHERE ds.Feeder11Id = :f_id
    AND m.Ts >= DATEADD(hour, -:hrs, @MaxDate)
    ORDER BY m.Ts
""")

params = {"f_id": 1, "hrs": 168}

with engine.connect() as conn:
    df = pd.read_sql(sql_query, conn, params=params)

print(f"Učitano je {len(df)} redova.")
df.head()

Učitano je 289 redova.

   meter_id         value                    timestamp
0     56206  4.067140e+09  2026-04-09 18:30:00.0000000
1     56206  4.067260e+09  2026-04-09 19:00:00.0000000
2     56206  4.067400e+09  2026-04-09 19:30:00.0000000
3     56206  4.067520e+09  2026-04-09 20:00:00.0000000
4     56206  4.067680e+09  2026-04-09 20:30:00.0000000

In [14]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [15]:
df.isna().sum()

meter_id     0
value        0
timestamp    0
dtype: int64

In [16]:
print(df.head())

   meter_id         value           timestamp
0     56206  4.067140e+09 2026-04-09 18:30:00
1     56206  4.067260e+09 2026-04-09 19:00:00
2     56206  4.067400e+09 2026-04-09 19:30:00
3     56206  4.067520e+09 2026-04-09 20:00:00
4     56206  4.067680e+09 2026-04-09 20:30:00

In [5]:
sql_query = text("SELECT Id, Name, SsId, MeterId, Feeder33Id, NameplateRating, TsId FROM dbo.Feeders11")

with engine.connect() as conn:
    df_feeders11 = pd.read_sql(sql_query, conn)

print(f"Učitano je {len(df_feeders11)} redova.")
df_feeders11.head(50)

Učitano je 435 redova.

,Id,Name,SsId,MeterId,Feeder33Id,NameplateRating,TsId
0,1,132KV KATAMPE TS_33KV WUSE II FDR_B5_1A,1.0,9.0,2.0,1000.0,NaN
1,2,132KV KATAMPE TS_33KV WUSE II FDR_B5_1B,1.0,6.0,2.0,1000.0,NaN
2,3,132KV KATAMPE TS_33KV WUSE II FDR_B5_2A,1.0,8.0,2.0,1000.0,NaN
3,4,132KV KATAMPE TS_33KV WUSE II FDR_B5_2B,1.0,11.0,2.0,1000.0,NaN
4,5,132KV KATAMPE TS_33KV WUSE II FDR_B5_3A,1.0,7.0,2.0,1000.0,NaN
5,6,132KV KATAMPE TS_33KV WUSE II FDR_B5_3B,1.0,13.0,2.0,1000.0,NaN
6,7,132KV KATAMPE TS_33KV WUSE II FDR_B5_4A,1.0,12.0,2.0,1000.0,NaN
7,8,132KV KATAMPE TS_33KV WUSE II FDR_B5_4B,1.0,10.0,2.0,1000.0,NaN
8,9,132KV KATAMPE TS_33KV WUSE II FDR_B52_1A,2.0,20.0,2.0,1000.0,NaN
9,10,132KV KATAMPE TS_33KV WUSE II FDR_B52_1B,2.0,16.0,2.0,1000.0,NaN
10,11,132KV KATAMPE TS_33KV WUSE II FDR_B52_2A,2.0,17.0,2.0,1000.0,NaN
11,12,132KV KATAMPE TS_33KV WUSE II FDR_B52_2B,2.0,15.0,2.0,1000.0,NaN
12,13,132KV KATAMPE TS_33KV WUSE II FDR_B52_3A,2.0,19.0,2.0,1000.0,NaN
13,14,132KV KATAMPE TS_33KV WUSE II FDR_B52_3B,2.0,21.0,2.0,1000.0,NaN
14,15,132KV KATAMPE TS_33KV WUSE II FDR_B52_4A,2.0,18.0,2.0,1000.0,NaN
15,16,132KV KATAMPE TS_33KV WUSE II FDR_B52_4B,2.0,14.0,2.0,1000.0,NaN
16,31,132KV APO TS_33KV FDR H1_G22_7LEFT,7.0,26691.0,8.0,NaN,NaN
17,32,132KV APO TS_33KV FDR H11_G4_1B,8.0,26722.0,113.0,1000.0,NaN
18,33,132KV APO TS_33KV FDR H11_G4_7B,8.0,26717.0,113.0,1000.0,NaN
19,34,132KV CENTRAL AREA TS_33KV FDR 5_G2_5B,5.0,26809.0,7.0,100.0,NaN
20,35,132KV CENTRAL AREA TS_33KV FDR 5_G42_FDL1,6.0,26807.0,7.0,NaN,NaN
21,36,33OKV APIR-LAFIA LINE 1&2_132KV AKURBA TS_33KV...,9.0,NaN,12.0,NaN,NaN
22,37,132KV GIS DAWAKI TS_33KV FDR D2_M42_K12,10.0,26665.0,118.0,1000.0,NaN
23,38,132KV GIS DAWAKI TS_33KV FDR D2_M42_K14,10.0,26657.0,118.0,1000.0,NaN
24,39,132KV GIS DAWAKI TS_33KV FDR D2_M42_K5,10.0,26668.0,118.0,1000.0,NaN
25,40,132KV GIS DAWAKI TS_33KV FDR D2_M42_K6,10.0,26666.0,118.0,1000.0,NaN
26,41,132KV GIS DAWAKI TS_33KV FDR D2_M43_ADKAN,11.0,26653.0,118.0,1000.0,NaN
27,42,132KV GIS DAWAKI TS_33KV FDR D2_M43_SETRACO,11.0,26671.0,118.0,1000.0,NaN
28,43,132KV KATAMPE 1 TS_33KV GWARINPA FDR_T1_LINE C,12.0,27057.0,14.0,1000.0,NaN
29,44,132KV KATAMPE 1 TS_33KV GWARINPA FDR_T1_LINE E,12.0,27054.0,14.0,1000.0,NaN
30,45,132KV KATAMPE 1 TS_33KV GWARINPA FDR_T1_LINE F,12.0,27058.0,14.0,1000.0,NaN
31,46,132KV KATAMPE 1 TS_33KV GWARINPA FDR_T1_LINE H,12.0,27053.0,14.0,1000.0,NaN
32,50,132KV APO TS_33KV FDR H1_G22_1LEFT,7.0,26688.0,8.0,NaN,NaN
33,51,132KV APO TS_33KV FDR H1_G22_2LEFT,7.0,26687.0,8.0,NaN,NaN
34,52,132KV APO TS_33KV FDR H1_G22_4LEFT,7.0,26683.0,8.0,NaN,NaN
35,53,132KV APO TS_33KV FDR H1_G22_5&8LEFT,7.0,26689.0,8.0,NaN,NaN
36,54,132KV APO TS_33KV FDR H1_G24_FD2,14.0,26719.0,8.0,NaN,NaN
37,55,132KV APO TS_33KV FDR H1_G24_FD5,14.0,26708.0,8.0,NaN,NaN
38,56,132KV APO TS_33KV FDR H1_G24_FDR 22,14.0,26705.0,8.0,NaN,NaN
39,57,132KV APO TS_33KV FDR H2_G32_1B,15.0,26711.0,19.0,NaN,NaN
40,58,132KV APO TS_33KV FDR H2_G32_2B,15.0,26752.0,19.0,NaN,NaN
41,59,132KV APO TS_33KV FDR H2_G32_3B,15.0,26715.0,19.0,NaN,NaN
42,60,132KV APO TS_33KV FDR H2_G32_5B,15.0,26753.0,19.0,NaN,NaN
43,61,132KV APO TS_33KV FDR H2_G32_6B,15.0,26701.0,19.0,NaN,NaN
44,62,132KV APO TS_33KV FDR H2_G32_7A,15.0,26758.0,19.0,NaN,NaN
45,63,132KV APO TS_33KV FDR H2_G32_8B,15.0,26695.0,19.0,NaN,NaN
46,64,132KV APO TS_33KV FDR H2_G32_9B,15.0,26757.0,19.0,NaN,NaN
47,65,132KV APO TS_33KV FDR H11_G4_2A,8.0,26740.0,113.0,1000.0,NaN
48,66,132KV APO TS_33KV FDR H11_G4_2B,8.0,26738.0,113.0,1000.0,NaN
49,67,132KV APO TS_33KV FDR H11_G4_3B,8.0,26745.0,113.0,1000.0,NaN

In [6]:
df_feeders11.isna().sum()

Id                   0
Name                 0
SsId                14
MeterId             56
Feeder33Id          15
NameplateRating    260
TsId               421
dtype: int64

In [7]:
invalid_rows = df_feeders11[(df_feeders11['SsId'] == 0) & (df_feeders11['TsId'] == 0)]

double_connected = df_feeders11[df_feeders11['SsId'].notna() & df_feeders11['TsId'].notna()]

both_exist = df_feeders11[
    df_feeders11['SsId'].notna() & (df_feeders11['SsId'] != 0) &
    df_feeders11['TsId'].notna() & (df_feeders11['TsId'] != 0)
]

print(f"SsId=0 i TsId=0: {len(invalid_rows)}")
print(f"SsId != 0 i TsId != 0: {len(double_connected)}")

SsId=0 i TsId=0: 0
SsId != 0 i TsId != 0: 0

In [8]:
import pandas as pd
import numpy as np

df_feeders11['NameplateRating'] = pd.to_numeric(df_feeders11['NameplateRating'], errors='coerce')
df_feeders11['SsId'] = pd.to_numeric(df_feeders11['SsId'], errors='coerce')
df_feeders11['TsId'] = pd.to_numeric(df_feeders11['TsId'], errors='coerce')

df_feeders11['NameplateRating'] = df_feeders11['NameplateRating'].replace(0, np.nan)

In [ ]:
def make_key(row):
    if pd.notnull(row['SsId']) and row['SsId'] != 0:
        return f"SS_{int(row['SsId'])}"
    elif pd.notnull(row['TsId']) and row['TsId'] != 0:
        return f"TS_{int(row['TsId'])}"
    return None

df_feeders11['TempKey'] = df_feeders11.apply(make_key, axis=1)

In [ ]:
df_feeders11['NameplateRating'] = df_feeders11['NameplateRating'].fillna(
    df_feeders11.groupby('TempKey')['NameplateRating'].transform('mean')
)

preostalo_nan = df_feeders11['NameplateRating'].isnull().sum()
if preostalo_nan > 0:
    print(f"Bilo je {preostalo_nan} stanica bez ijednog podatka. Popunjavam globalnim prosekom.")
    df_feeders11['NameplateRating'] = df_feeders11['NameplateRating'].fillna(df_feeders11['NameplateRating'].mean())

print(f"Konačan broj NaN vrednosti: {df_feeders11['NameplateRating'].isnull().sum()}")

Bilo je 121 stanica bez ijednog podatka. Popunjavam globalnim prosekom.
Konačan broj NaN vrednosti: 0

In [11]:
df_feeders11.isna().sum()

Id                   0
Name                 0
SsId                14
MeterId             56
Feeder33Id          15
NameplateRating      0
TsId               421
PrivremeniKljuc      0
dtype: int64

In [12]:
df_feeders11.shape

(435, 8)